name: skycast
description: "Flutter weather application"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_screenutil: ^5.9.3
  http: ^1.2.2
  flutter_riverpod: ^2.5.1
  geolocator: ^13.0.1
  intl: ^0.19.0
  cached_network_image: ^3.4.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.1
  flutter_lints: ^4.0.0


flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/app_logo.png"
  web:
    generate: true
    image_path: "assets/images/app_logo.png"
  macos:
    generate: true
    image_path: "assets/images/app_logo.png"
    icon_size: 48



flutter:
  uses-material-design: true
  assets:
    - assets/images/

